title: Programming Blog
subtitle: 
link: http://xx.xx.com
meta:
  description: 页面meta中的description
  keywords: !!seq
    - security
    - programming
    - interview
  author: zf
master:
  name: zf
  about: something about me
  email: xx@xx.com
rss:
  title: RSS源标题
  desc: RSS源描述
  lang: zh-cn
  max: 10
copyright:
  owner: 版权所有方
  beginYear: 2011
  endYear: 2013
  ICP: 备案号
theme: default
